site_name: Raspberry Pi SenseHat Snake Game
site_url: ''
use_directory_urls: False
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_url: https://github.com/TheNoobInventor/rpi-sensehat-snake-game
repo_name: TheNoobInventor/rpi-sensehat-snake-game
plugins:
  - search:
      lang: en
